"""empty message

Revision ID: 412098928adb
Revises: 
Create Date: 2022-11-22 15:52:15.088301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412098928adb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saveactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('activities_users_id_fkey', 'activities', type_='foreignkey')
    op.drop_column('activities', 'users_id')
    op.add_column('matches', sa.Column('match_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'match_id')
    op.add_column('activities', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('activities_users_id_fkey', 'activities', 'users', ['users_id'], ['id'], ondelete='CASCADE')
    op.drop_table('saveactivity')
    # ### end Alembic commands ###
