"""empty message

Revision ID: 46f21b5828cf
Revises: c3c2dfc8f469
Create Date: 2022-10-26 21:05:08.423050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f21b5828cf'
down_revision = 'c3c2dfc8f469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.alter_column('galleries', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('galleries', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trekking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gastronomy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cultural', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nightlife', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('shopping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('trips_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trips_id'], ['mytrips.id'], name='activities_trips_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='activities_pkey')
    )
    # ### end Alembic commands ###
