"""empty message

Revision ID: 6325026bb104
Revises: 
Create Date: 2022-10-24 16:01:24.796166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6325026bb104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('birthdate', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('languages', sa.NullType(), nullable=True),
    sa.Column('countryofresidence', sa.NullType(), nullable=True),
    sa.Column('socialmedia', sa.NullType(), nullable=True),
    sa.Column('photos', sa.NullType(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mytrips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travelling', sa.Integer(), nullable=False),
    sa.Column('with_children', sa.Boolean(), nullable=False),
    sa.Column('gender_specific', sa.Integer(), nullable=False),
    sa.Column('stay', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('partner_age', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trekking', sa.Boolean(), nullable=True),
    sa.Column('gastronomy', sa.Boolean(), nullable=True),
    sa.Column('cultural', sa.Boolean(), nullable=True),
    sa.Column('nightlife', sa.Boolean(), nullable=True),
    sa.Column('shopping', sa.Boolean(), nullable=True),
    sa.Column('trips_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trips_id'], ['mytrips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('mytrips')
    op.drop_table('users')
    # ### end Alembic commands ###
