"""empty message

Revision ID: d5bbc179967f
Revises: 3401f06ed8b8
Create Date: 2022-10-24 20:19:59.266158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bbc179967f'
down_revision = '3401f06ed8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('instagram', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('facebook', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('twitter', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['twitter'])
    op.create_unique_constraint(None, 'users', ['instagram'])
    op.create_unique_constraint(None, 'users', ['facebook'])
    op.drop_column('users', 'photos')
    op.drop_column('users', 'socialmedia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('socialmedia', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('photos', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'twitter')
    op.drop_column('users', 'facebook')
    op.drop_column('users', 'instagram')
    op.drop_table('galleries')
    # ### end Alembic commands ###
