"""empty message

Revision ID: e40234f99193
Revises: 
Create Date: 2022-10-28 00:46:04.995308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40234f99193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mytrips', sa.Column('activities', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mytrips', 'activities')
    # ### end Alembic commands ###
