"""empty message

Revision ID: fd988391bf7a
Revises: b7c182df3d65
Create Date: 2022-10-25 14:48:41.656710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd988391bf7a'
down_revision = 'b7c182df3d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('galleries', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable='False')
    op.add_column('users', sa.Column('instagram', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('facebook', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('twitter', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['facebook'])
    op.create_unique_constraint(None, 'users', ['twitter'])
    op.create_unique_constraint(None, 'users', ['instagram'])
    op.drop_column('users', 'photos')
    op.drop_column('users', 'socialmedia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('socialmedia', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('photos', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'twitter')
    op.drop_column('users', 'facebook')
    op.drop_column('users', 'instagram')
    op.alter_column('galleries', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
